# Generated by Django 3.1.4 on 2021-01-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_auto_20210127_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='publicado',
        ),
        migrations.AlterField(
            model_name='autor',
            name='sexo',
            field=models.BooleanField(),
        ),
    ]
