# Generated by Django 3.1.4 on 2021-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_autors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='apellido',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='autor',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=110),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pais',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='autor',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
    ]
